backend:
  name: github
  repo: git703742/bashakstudio
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "تنظیمات سایت"

    files:
      - label: "اطلاعات اصلی"
        name: "site"
        file: "content/site.yml"

        fields:
          - { label: "نام", name: "name", widget: "string" }
          - { label: "توضیحات", name: "bio", widget: "text" }

  - name: "projects"
    label: "پروژه ها"

    folder: "content/projects"
    create: true

    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "عکس", name: "image", widget: "image" }
      - { label: "توضیح", name: "description", widget: "text" }
